### ISSUE TITLE
Csound For Android is broken

### ISSUE THREAD

**Issue by ErrorThink** [gogins/csound-extended#65]
For the current release in the Play Store (labelled 6.11.1, but console reports --Csound version 6.13 (float samples) Nov  7 2018):
Csound doesn't run any CSD. 
Console messages of interest say
Warning: Csound not ready for performance: Csound Start has not been called.
then ... various functions return with -1
However, it does say 0 errors in performance, although amplitudes are always 0.
For what it's worth, I sometimes saw this happen with the previous version, but only if I stopped Csound, and started it very quickly (like it hadn't had time to close and cleanup something). Now however, it does this all the time.
Also can't seem to load any of the examples. Might be a separate issue?

**Comment by gogins** [comment]
File permissions in the Android API have changed. Sharing private files, such as the Csound examples in the app, or sharing files with other applications, such as the text editor required by the Csound app, both must be implemented using a FileProvider object, which must be explicitly configured in the application manifest and resources. 

This was all working up until I heard from you... I tested every one of the examples in the app menu successfully.

The errors you see are Csound running without an actual file, because the FileProvider refused to provide it.

**Comment by gogins** [comment]
I think it's just permissions. Go to the device settings and give the Csound app storage permission. I'll see why the app manifest didn't do this automatically but everything is working for me now.

**Comment by gogins** [comment]
Runtime requests (Android 6.0 and higher)
If the device is running Android 6.0 (API level 23) or higher, and the app's targetSdkVersion is 23 or higher, the user isn't notified of any app permissions at install time. Your app must ask the user to grant the dangerous permissions at runtime. When your app requests permission, the user sees a system dialog (as shown in figure 1, left) telling the user which permission group your app is trying to access. The dialog includes a Deny and Allow button.

If the user denies the permission request, the next time your app requests the permission, the dialog contains a checkbox that, when checked, indicates the user doesn't want to be prompted for the permission again (see figure 1, right).

**Comment by gogins** [comment]
https://developer.android.com/training/permissions/requesting

This will fix it.

**Comment by ErrorThink** [comment]
Yes, granting permissions fixes everything. Much obliged.

**Comment by gogins** [comment]
I have modified the app to automatically ask for permissions if the user has not already configured them. The app has been re-published to the Play Store.
